### ISSUE TITLE
WikiページにおけるMimeタイプ設定機能

### ISSUE THREAD

**Issue by MirrgieRiana** [ukatama/mew#2]
記事内におけるHTMLの埋め込みで、別の記事のmarkdownソースを表すURL（&c=markdown　指定）を外部CSSファイルとして指定したいです。
しかし、HTMLにおいて、外部CSSファイルへの参照として指定するURLのリソースのMimeタイプは、CSSのものでなければならないようで、それは不可能でした。

現状ではすべてのCSSを埋め込んでいる記事はCSSがそのまま埋め込まれていますが、これを別の記事のソースを外部CSSとして利用できるようにしませんか？

**Comment by esnya** [comment]
ちょっとWiki本来の用法とは外れるので・・・
ちょっと視点を変えて他のページの埋め込み機能（C言語のincludeのような）などはいかが？

[MultiMarkdown](http://fletcher.github.io/MultiMarkdown-4/transclusion.html)から文法を借りて

```
{{path/to/page}}
```

などでその場所にページ `path/to/page` のMarkdownを埋め込むような形。

参照先のMarkdownにstyleタグを埋め込んでおけば目的は達成できるのではないでしょうか。

**Comment by MirrgieRiana** [comment]
:+1:

**Comment by esnya** [comment]
Add transclusion syntax ded9f5bb14ddeec2cb97165ec200e28e8d814348

**Comment by MirrgieRiana** [comment]
Thank you
